org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.http.keepAlive=true
systemProp.https.keepAlive=true
android.experimental.properties.version.check=false
android.disallowKotlinSourceSets=false
kapt.use.jvm.ir=true
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
